RBFOX_BAMS:
  rep1:
    bam_files/Rbfox2_CLIP_S24_L001_r1.bam
  rep2:
    bam_files/RBFOX2_CLIP_S31_L002_r1.bam
INPUT_BAMS:
  rep1:
    bam_files/Rbfox2_IN_S26_L001_r1.bam
  rep2:
    bam_files/RBFOX2_INPUT_S29_L002_r1.bam